### ISSUE TITLE
Add option to not scale some icons

### ISSUE THREAD

**Issue by fwsmit** [dunst-project/dunst#1037]
With the introduction of the recursive icon lookup, all the icons will get scaled to a certain size, `icon_size`. For scalable icons this is no problem, since they are scalable without getting blurry. For other icons this is more of a problem. Icons that are sent as raw icons via dbus will never be scalable and icons that are sent via path name might be scalable.

There are a few options to make sure icons don't get scaled badly:

- Add a `max_icon_size` option again (as a rule).
- Add a `scale_raw_icons` rule which can be set to false to not get blurry icons.
- More?

ref #992

**Comment by fwsmit** [comment]
Sounds like a good approach! Thanks for you input. I think I'll explore this direction.

**Comment by J-MR-T** [comment]
It would also be possible to add an option in the commandline tools, a hint for `notify-send` and a native option for `dunstify` to force a certain icon size. I am currently struggling with the new recursive icon lookup, because icons for volume and brightness notifications need to be way smaller than the cover art for song-change notifications. 

Currently I cannot get the song-change notification icons big, without  screwing up all other notifications, as `icon_size` doesn't seem to be responsible for scaling, but is the only option available to set rule based. I think the easiest, most transparent and accessible option would be a hard override on the commandline. 

But I am open to being corrected here, as this might go against some paradigms of dunst that I'm unfamiliar with.

**Comment by fwsmit** [comment]
> Suggestion: only have two options `min_icon_size` and `max_icon_size`, both global and per-rule. For named icons, use `min_icon_size` to query the icon, then scale between the bounds. For raw icons, just scale between the bounds.

This has been implemented in #1069.

> Crucially, allow rules to match on whether the icon is named or raw (and maybe on whether it's an SVG, though I'm not sure why this is useful).

It would be nice I guess, but I don't consider this a priority.



> It would also be possible to add an option in the commandline tools, a hint for `notify-send` and a native option for `dunstify` to force a certain icon size. I am currently struggling with the new recursive icon lookup, because icons for volume and brightness notifications need to be way smaller than the cover art for song-change notifications.
> 
> Currently I cannot get the song-change notification icons big, without screwing up all other notifications, as `icon_size` doesn't seem to be responsible for scaling, but is the only option available to set rule based. I think the easiest, most transparent and accessible option would be a hard override on the commandline.
> 
> But I am open to being corrected here, as this might go against some paradigms of dunst that I'm unfamiliar with.


> It would also be possible to add an option in the commandline tools, a hint for `notify-send` and a native option for `dunstify` to force a certain icon size. I am currently struggling with the new recursive icon lookup, because icons for volume and brightness notifications need to be way smaller than the cover art for song-change notifications.
> 
> Currently I cannot get the song-change notification icons big, without screwing up all other notifications, as `icon_size` doesn't seem to be responsible for scaling, but is the only option available to set rule based. I think the easiest, most transparent and accessible option would be a hard override on the commandline.
> 
> But I am open to being corrected here, as this might go against some paradigms of dunst that I'm unfamiliar with.

I think with the `min_icon_size` and `max_icon_size` it should be flexible enough again, so I don't think a hint is neccesary.

**Comment by ncfavier** [comment]
I still don't know how to do what I'm after, with the recent changes.

As a reminder, I want to be able to use dunst to display two separate kinds of icons:

- raw icons: things like album arts or screenshots, which should be "large" (scaled down to 500 pixels tall)
- named icons: these should be looked up in the icon theme according to a given size (in my case 64 px), and scaled to that size

This is why I need rules to be able to match on whether the icon is raw or not, and set sizes accordingly. Is this hard to implement?

**Comment by fwsmit** [comment]
Since `min_icon_size` is used for looking up named icons your use case can be achieved with:
dunstrc:
```ini
[global]
min_icon_size=64
max_icon_size=500
```

**Comment by ncfavier** [comment]
But that will scale SVG icons up to 500 pixels!

**Comment by fwsmit** [comment]
You mean named svg icons? It should scale all named icons to 64 pixels

**Comment by ncfavier** [comment]
`dunstify -i dialog-information a`:

![](https://f.monade.li/25Blks.png)

**Comment by fwsmit** [comment]
Could you try that with the latest dunst-git. I think that issue has been resolved? I cannot reproduce it at least. Otherwise, please open a new bug report describing how to reproduce this issue.
